name: 'dacsslide_starter'
version: 0.0.1
description: DaCSSlide starter project
#author: <your name> <email@example.com>
homepage: https://github.com/olostan/dacsslide_starter
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: '>=1.0.0 <1.2.0'
  browser: '>=0.10.0 <0.11.0'
  dacsslide: 'any'
  csslib_transform: '>=0.0.1 <0.1.0'
  pretty_samples: 'any'
transformers:
- angular
- dacsslide
- csslib_transform